name: native_animated_image_windows
description: Windows implementation of native_animated_image (ships the Rust native binary).
version: 0.3.0
repository: https://github.com/Lingyan000/native_animated_image

resolution: workspace

environment:
  sdk: ^3.6.0
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      windows:
        ffiPlugin: true
